# Generated by Django 4.1.7 on 2023-02-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-1-1'),
            preserve_default=False,
        ),
    ]
